# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Appium Run CI

on:
  push:
    branches: [ "lp/apredendendo-CI/CD" ]
  pull_request:
    branches: [ "lp/apredendendo-CI/CD" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        api-level: [33]
        target: [default]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install and Run Appium Server
      run: |
        chmod +x ./scripts/appium-server.sh
        ./scripts/appium-server.sh
        sudo groupadd -r kvm
        sudo gpasswd -a $USER kvm

    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
        script: npm test
