name: Appium Run CI

on:
  push:
    branches: [ "lp/apredendendo-CI/CD" ]
  pull_request:
    branches: [ "lp/apredendendo-CI/CD" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.0.0]
        api-level: [33]
        target: [default]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: |
        npm install
        sudo apt install adb
        sudo adb kill-server
        sudo adb start-server

    - name: Install and Run Appium Server
      run: |
        chmod +x ./scripts/appium-server.sh
        ./scripts/appium-server.sh &

    - name: Wait for Appium to Start
      run: sleep 5  # Aguarde alguns segundos para o Appium iniciar completamente

    - name: Wait for Emulator to Start
      run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done'

    - name: Start Emulator
      uses: reactivecircus/android-emulator-runner@v2.27.0
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        ram-size: 4096M
        heap-size: 1024M
        emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
        script: chmod +x ./scripts/appium-tests.sh
                ./scripts/appium-tests.sh
