name: Appium Run CI

on:
  push:
    branches: [ "lp/apredendendo-CI/CD" ]
  pull_request:
    branches: [ "lp/apredendendo-CI/CD" ]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Set up JDK 8
          uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: '8'

        - name: Install and Run Appium Server
          run: |
            chmod +x ./scripts/appium-server.sh
            ./scripts/appium-server.sh &

        - name: Download and Extract Emulator
          run: |
              curl -sL https://dl.google.com/android/repository/emulator-linux-7306070.zip -o emulator.zip
              mkdir -p $HOME/android-sdk
              tar -xzf emulator.zip -C $HOME/android-sdk
              export PATH="$HOME/android-sdk/emulator:$HOME/android-sdk/tools:$PATH"
              emulator -version

        - name: Start Emulator
          run: |
            sdkmanager --list
            sdkmanager "system-images;android-29;google_apis;x86_64"
            echo no | avdmanager create avd -n test -k "system-images;android-29;google_apis;x86_64"
            emulator -avd test -no-window -no-audio -no-snapshot -no-accel -gpu swiftshader

        - name: Install Dependencies
          run: |
            echo y | sdkmanager "platform-tools" "build-tools;29.0.2" "extras;google;m2repository" "extras;android;m2repository"

        - name: Build and Run Appium Tests
          run: |
            chmod +x ./scripts/appium-tests.sh
            ./scripts/appium-tests.sh
