name: Appium Run CI

on:
  push:
    branches: [ "lp/apredendendo-CI/CD" ]
  pull_request:
    branches: [ "lp/apredendendo-CI/CD" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.0.0]
        api-level: [33]
        target: [default]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Install and Run Appium Server
      run: |
        chmod +x ./scripts/appium-server.sh
        ./scripts/appium-server.sh &

    - name: Wait for Appium to Start
      run: sleep 8

    - name: Add new user to group KVM
      run: |
        sudo usermod -aG kvm runner
        sudo gpasswd -a $USER kvm
        sudo newgrp kvm

    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v2.28.0
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        ram-size: 4096M
        heap-size: 1024M
        emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
        script: |
            chmod +x ./scripts/appium-tests.sh
            ./scripts/appium-tests.sh
