name: Check User

on:
  push:
    branches: [ "lp/apredendendo-CI/CD" ]

jobs:
  check_user:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check user
      run: |
        whoami
